numpy:
  - 1.26
libprotobuf:
  - 5.29.3
protobuf:
  - 5.29.3
spdlog:
  - 1.15
pugixml:
  - '1.15'
libopencv:
  - 4.11.0
libxml2:
  - 2.13.*
graphviz:
  - 12.*
cmake:
  - 3.*

cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.10.*
python_impl:
  - cpython

emscripten_emscripten-wasm32:
  - 3.1.45
cross-python_emscripten-wasm32:
  - 3.11.* *_12

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2022                     # [win]
  - emscripten                 # [emscripten]
c_compiler_version:            # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2022                     # [win]
  - emscripten                 # [emscripten]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]

libzenohc:
  - 1.4.0
libzenohcxx:
  - 1.4.0
libcap:
  - 2.71
