version: '3.8'

services:
  robostack-dev:
    image: ghcr.io/prefix-dev/pixi:latest
    container_name: robostack-dev
    volumes:
      # Mount the entire workspace
      - .:/workspace
    working_dir: /workspace
    # Keep container running with an interactive shell
    command: sleep infinity
    tty: true
    stdin_open: true