[project]
name = "ros-humble"
# Just a convention, this is the same as the mutex package
version = "0.7.0"
description = "RoboStack repo to package ros-humble packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>", "Daniel Hou <houhd@umich.edu>"]
channels = ["conda-forge", "robostack-staging", "https://repo.prefix.dev/robostack-staging", "https://repo.prefix.dev/robostack-humble"]
platforms = ["linux-64"]

[system-requirements]
# 2.17 is the glibc version used in centos 7
libc = { family="glibc", version="2.17" }

[dependencies]
python = ">=3.11.0,<3.12"
rattler-build = ">=0.44.0"
anaconda-client = ">=1.12"

# [target.win-64.dependencies]
# # patch is required by rattler-build
# m2-patch = "*"
# # git is required by rattler-build
# git = "*"

[pypi-dependencies]
# This is tipically the latest commit on main branch
vinca = { git = "https://github.com/RoboStack/vinca.git", rev = "c534eca68a77bc5cc34e3ddfb27715c8b0a66907" }
# Uncomment this line to work with a local vinca for faster iteration, but remember to comment it back
# (and regenerate the pixi.lock) once you push the modified commit to the repo
#vinca = { path = "../vinca", editable = true }

[tasks]
upload = "anaconda -t $ANACONDA_API_TOKEN upload"
generate-recipes = { cmd = "vinca -m" } # , depends-on = ["remove-file"] }
check-patches = { cmd = "python check_patches_clean_apply.py", depends-on = ["generate-recipes"] }
generate-recipes-emscripten = { cmd = "vinca -m --platform emscripten-wasm32", depends-on = ["remove-file"] }
check-patches-emscripten = { cmd = "python check_patches_clean_apply.py", depends-on = ["generate-recipes-emscripten"] }
remove-file = { cmd = "rm -rf recipes; mkdir recipes" }
build = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c https://repo.prefix.dev/conda-forge -c robostack-staging  --skip-existing", depends-on = ["generate-recipes"] }
build_one_package = { cmd = "cp ./patch/$PACKAGE.*patch ./recipes/$PACKAGE/patch/; rattler-build build --recipe ./recipes/$PACKAGE/recipe.yaml -m ./conda_build_config.yaml -c https://repo.prefix.dev/conda-forge -c robostack-staging", env = { PACKAGE = "ros-humble-ros-workspace" } }
create_snapshot = { cmd = "vinca-snapshot" }


[tasks.build-emscripten]
  cmd = [
      "rattler-build", "build",
      "--package-format", "tar-bz2",
      "--recipe-dir", "./recipes",
      "-m", "./conda_build_config.yaml",
      "-c", "conda-forge",
      "-c", "https://repo.mamba.pm/emscripten-forge",
      "-c", "robostack-staging",
      "--target-platform", "emscripten-wasm32",
      "--skip-existing",
      "--test", "skip"
      ]
  depends-on = ["generate-recipes-emscripten"]
