package:
  name: ros-humble-victor-policy-client
  version: 0.0.1
about:
  homepage: https://www.ros.org/
  license: MIT
  summary: Lightweight policy client for Victor robot with minimal dependencies
  maintainers: []
extra:
  recipe-maintainers:
    - robostack
build:
  number: 0
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
source:
  path: ../../custom_packages/kuka_iiwa_interface/victor_policy_client
  target_directory: ros-humble-victor-policy-client/src/work
requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python==3.10
    - pip
    - patch
    - if: unix
      then:
        - make
        - coreutils
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - cython
    - if: build_platform != target_platform
      then:
        - numpy
    - if: build_platform != target_platform
      then:
        - pybind11
  host:
    - python==3.10
    - pip
    - ros-humble-rclpy
    - ros-humble-geometry-msgs
    - ros-humble-std-msgs
    - ros-humble-ament-copyright
    - ros-humble-ament-flake8
    - ros-humble-ament-pep257
    - pytest
  run:
    - python==3.10
    - ros-humble-rclpy
    - ros-humble-geometry-msgs
    - ros-humble-std-msgs
