# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: ros-humble-victor-hardware-interfaces
  version: 1.0.0

source:
  - path: ../../custom_packages/kuka_iiwa_interface/victor_hardware_interfaces
    target_directory: ros-humble-victor-hardware-interfaces/src/work

build:
  number: 10

  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

outputs:
  - package:
      name: ros-humble-victor-hardware-interfaces
      version: 1.0.0
    about:
      homepage: https://arm.robotics.umich.edu/
      license: BSD-3-Clause
      summary: Message and service definitions for victor.
      maintainers: []
    extra:
      recipe-maintainers:
        - UM-ARM-Lab
    build:
      number: 0
      script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - if: target_platform!='emscripten-wasm32'
          then:
            - ${{ stdlib('c') }}
        - ninja
        - python
        - patch
        - libxcrypt
        - if: unix
          then:
            - make
            - coreutils
        - cmake
        - if: build_platform != target_platform
          then:
            - python
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
        - if: build_platform != target_platform
          then:
            - cython
        - if: build_platform != target_platform
          then:
            - numpy
        - if: build_platform != target_platform
          then:
            - pybind11
        - python==3.10
        - ros-humble-rosidl-default-generators
        - ros-humble-rosidl-typesupport-c
        - ros-humble-rosidl-typesupport-cpp
        - ros-humble-rosidl-generator-py
      host:
        - python==3.10
        - libxcrypt
        - ros-humble-ament-cmake
        - ros-humble-rosidl-default-generators
        - ros-humble-geometry-msgs
        - ros-humble-std-msgs
        - ros-humble-geometry-msgs
        - ros-humble-std-msgs
        - ros-humble-rosidl-default-generators
        - ros-humble-rosidl-typesupport-c
        - ros-humble-rosidl-typesupport-cpp
        - ros-humble-rosidl-generator-py
      run:
        - python==3.10
        - ros-humble-geometry-msgs
        - ros-humble-std-msgs
        - ros-humble-rosidl-default-runtime
        - ros-humble-geometry-msgs
        - ros-humble-std-msgs
        - ros-humble-rosidl-default-generators
        - ros-humble-rosidl-typesupport-c
        - ros-humble-rosidl-typesupport-cpp
        - ros-humble-rosidl-generator-py
